version: '2'

services:
  nginx-php-fpm:
    build: .
    volumes:
      - ./DATA:/var/www/gsales/DATA
    links:
      - mariadb
    environment:
      - MYSQL_DATABASE=databaseName
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - SMTP_HOST=hostname
      - SMTP_PORT=25
      - SMTP_SECURITY=ssl
      - SMTP_USERNAME=username
      - SMTP_PASSWORD=password
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=databaseName
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password