version: '2'

services:
  nginx-php-fpm:
    restart: always
    image: muensmedia/gsales:latest
    volumes:
      - ./DATA:/var/www/gsales/DATA
    links:
      - mariadb
    networks:
      - traefik
      - internal
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_SECURITY: $SMTP_SECURITY
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD

      PUID: $PUID
      PGID: $PGID
    labels:
      - "traefik.http.routers.gsales2_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mariadb:
    restart: always
    image: mariadb:latest
    volumes:
      - mariadb-vol-1:/var/lib/mysql/
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD

volumes:
  mariadb-vol-1:

networks:
  traefik:
    external: true
  internal:
    external: false